//Console.WriteLine($"{Math.PI:F2}");
//Console.WriteLine($"{Math.E:F1}");
//Console.WriteLine("введите число");
//int n = int.Parse(Console.ReadLine());
//Console.WriteLine($"вы ввели число {n}");
//Console.WriteLine($"{7}  {15}  {100}");
//Console.WriteLine("введите три числа");
//int a = int.Parse(Console.ReadLine());
//int b = int.Parse(Console.ReadLine());
//int c = int.Parse(Console.ReadLine());
//Console.WriteLine($"вы ввели {a}  {b}  {c}");
//Console.WriteLine("50\n10");
//Console.WriteLine("5\n10\n21");
//Console.WriteLine("Введите две переменные");
//int t = int.Parse(Console.ReadLine());
//int v = int.Parse(Console.ReadLine());
//Console.WriteLine("5 10\n 7см");
//Console.WriteLine($"100 {t}\n1949 {v}");
//Console.WriteLine("Введите две переменные");
//int x = int.Parse(Console.ReadLine());
//int y = int.Parse(Console.ReadLine());
//Console.WriteLine($"{x} 25\n{x} {y}");
//1.17
//Console.WriteLine("Введите x1");
//double x1 = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите x2");
//double x2 = double.Parse(Console.ReadLine());
//double res = Math.Sqrt(x1 * x1 + x2 * x2);
//Console.WriteLine($"Результат={res:F2}");
//Console.WriteLine("Введите v0");
//double v0 = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите t");
//double t = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите a");
//double a = double.Parse(Console.ReadLine());
//double s = v0 * t + (a * t * t) / 2;
//Console.WriteLine($"s={s:F2}");
//Console.WriteLine("Введите m");
//double m = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите v");
//double v = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите g");
//double g = double.Parse(Console.ReadLine());
//Console.WriteLine("Введите h");
//double h = double.Parse(Console.ReadLine());
//double s = (m * v*v) / 2 + v * g * h;
//Console.WriteLine($"s={s:F2}");
//Console.WriteLine("Введите x");
//double x = double.Parse(Console.ReadLine());
//double y = 7 * x * x - 3 * x + 6;
//Console.WriteLine($"y={y:F2}");
Console.WriteLine("Добиться успеха легко, познать смысл - вот проблема");
string str = "Добиться успеха легко, познать смысл - вот проблема";
Console.WriteLine("До: " + str);
Console.WriteLine("После: " + str.Insert(23, "но "));