Console.WriteLine($"{Math.PI:F2}");
Console.WriteLine($"{Math.E:F1}");
Console.WriteLine("введите число");
int n = int.Parse(Console.ReadLine());
Console.WriteLine($"вы ввели число {n}");
Console.WriteLine($"{7}  {15}  {100}");
Console.WriteLine("введите три числа");
int a = int.Parse(Console.ReadLine());
int b = int.Parse(Console.ReadLine());
int c = int.Parse(Console.ReadLine());
Console.WriteLine($"вы ввели {a}  {b}  {c}");
Console.WriteLine("50\n10");
Console.WriteLine("5\n10\n21");
Console.WriteLine("Введите две переменные");
int t = int.Parse(Console.ReadLine());
int v = int.Parse(Console.ReadLine());
Console.WriteLine("5 10\n 7см");
Console.WriteLine($"100 {t}\n1949 {v}");
Console.WriteLine("Введите две переменные");
int x = int.Parse(Console.ReadLine());
int y = int.Parse(Console.ReadLine());
Console.WriteLine($"{x} 25\n{x} {y}");